import type { Level } from "./levelTypes"
import backgroundImage from "../assets/arcade_bckgrnd_startscreen.png"
import music from "../assets/Neon Run.mp3"

const levelOne: Level = {
  backgroundImage,
  music,
  name: "Neon Highway",
  style: "neon-arcade",
  obstacles: [
    {
      id: 1,
      type: "obstacle",
      note: "A#",
      string: "A",
      fret: 1,
      positionX: 100,
      positionY: 20,
      width: 5,
      height: 8,
    },
    {
      id: 2,
      type: "obstacle",
      positionX: 120,
      positionY: 30,
      width: 5,
      height: 8,
    },
    {
      id: 3,
      type: "obstacle",
      note: "C#",
      string: "A",
      fret: 4,
      positionX: 140,
      positionY: 40,
      width: 5,
      height: 8,
    },
    {
      id: 4,
      type: "obstacle",
      note: "C",
      string: "A",
      fret: 3,
      positionX: 340.3,
      positionY: 20,
      width: 8,
      height: 8,
    },
    {
      id: 5,
      type: "spike",
      note: "D#",
      string: "D",
      fret: 1,
      positionX: 421.3,
      positionY: 20,
      width: 5,
      height: 8,
    },
    {
      id: 6,
      type: "spike",
      note: "C#",
      string: "A",
      fret: 4,
      positionX: 502.3,
      positionY: 20,
      width: 5,
      height: 8,
    },
    {
      id: 7,
      type: "spike",
      note: "E",
      string: "Tiefe E",
      fret: 0,
      positionX: 583.5,
      positionY: 20,
      width: 5,
      height: 8,
    },
    {
      id: 8,
      type: "obstacle",
      note: "C#",
      string: "A",
      fret: 4,
      positionX: 664.5,
      positionY: 20,
      width: 8,
      height: 8,
    },
    {
      id: 9,
      type: "crouch",
      note: "E",
      string: "Tiefe E",
      fret: 0,
      positionX: 745.8,
      positionY: 30,
      width: 10,
      height: 5,
    },
    {
      id: 10,
      type: "spike",
      note: "E",
      string: "Tiefe E",
      fret: 0,
      positionX: 826.7,
      positionY: 20,
      width: 5,
      height: 8,
    },


  ]
}

export default levelOne