import type { Level } from "./levelTypes"
import backgroundImage from "../assets/arcade_bckgrnd_startscreen.png"
import music from "../assets/Neon Run.mp3"

const levelOne: Level = {
  backgroundImage,
  music,
  name: "Neon Highway (Lvl.1)",
  style: "neon-arcade",
  obstacles: [
    {
      id: 1,
      type: "spike",
      note: "E",
      string: "Tiefe E",
      fret: 0,
      positionX: 70,
      positionY: 20,
      width: 5,
      height: 8,
    },
    {
      id: 2,
      type: "spike",
      note: "G",
      string: "Tiefe E",
      fret: 3,
      positionX: 140,
      positionY: 20,
      width: 5,
      height: 8,
    },
    {
      id: 3,
      type: "spike",
      note: "A",
      string: "Tiefe E",
      fret: 5,
      positionX: 210,
      positionY: 20,
      width: 5,
      height: 8,
    },

    {
      id: 4,
      type: "obstacle",
      note: "E",
      string: "Tiefe E",
      fret: 0,
      positionX: 300,
      positionY: 20,
      width: 130,
      height: 8,
    },
    {
      id: 5,
      type: "spike",
      note: "G",
      string: "Tiefe E",
      fret: 3,
      positionX: 370,
      positionY: 28,
      width: 5,
      height: 8,
    },
    {
      id: 6,
      type: "obstacle",
      note: "A",
      string: "Tiefe E",
      fret: 5,
      positionX: 440,
      positionY: 28,
      width: 80,
      height: 8,
    },
    {
      id: 7,
      type: "obstacle",
      note: "A",
      string: "Tiefe E",
      fret: 5,
      positionX: 530,
      positionY: 36,
      width: 60,
      height: 8,
    },
    {
      id: 8,
      type: "spike",
      note: "G",
      string: "Tiefe E",
      fret: 3,
      positionX: 600,
      positionY: 20,
      width: 5,
      height: 8,
    },
    {
      id: 9,
      type: "crouch",
      note: "E",
      string: "Tiefe E",
      fret: 0,
      positionX: 670,
      positionY: 30,
      width: 60,
      height: 8,
    },
    {
      id: 10,
      type: "spike",
      note: "E",
      string: "Tiefe E",
      fret: 0,
      positionX: 760,
      positionY: 20,
      width: 5,
      height: 8,
    },
    {
      id: 11,
      type: "obstacle",
      note: "A",
      string: "Tiefe E",
      fret: 5,
      positionX: 850,
      positionY: 20,
      width: 85,
      height: 8,
    },
    {
      id: 12,
      type: "obstacle",
      note: "E",
      string: "Tiefe E",
      fret: 0,
      positionX: 940,
      positionY: 32,
      width: 80,
      height: 8,
    },
    {
      id: 13,
      type: "obstacle",
      note: "E",
      string: "Tiefe E",
      fret: 0,
      positionX: 1030,
      positionY: 44,
      width: 130,
      height: 8,
    },
    {
      id: 14,
      type: "spike",
      note: "G",
      string: "Tiefe E",
      fret: 3,
      positionX: 1100,
      positionY: 52,
      width: 5,
      height: 8,
    },
    {
      id: 15,
      type: "spike",
      note: "A",
      string: "Tiefe E",
      fret: 5,
      positionX: 1180,
      positionY: 20,
      width: 5,
      height: 8,
    },

    {
      id: 16,
      type: "obstacle",
      note: "E",
      string: "Tiefe E",
      fret: 0,
      positionX: 1250,
      positionY: 20,
      width: 70,
      height: 8,
    },
    {
      id: 17,
      type: "obstacle",
      note: "G",
      string: "Tiefe E",
      fret: 3,
      positionX: 1320,
      positionY: 28,
      width: 70,
      height: 8,
    },
    {
      id: 18,
      type: "obstacle",
      note: "A",
      string: "Tiefe E",
      fret: 5,
      positionX: 1390,
      positionY: 39,
      width: 70,
      height: 8,
    },
    {
      id: 19,
      type: "coin",
      positionX: 1460,
      positionY: 42,
      width: 8,
      height: 8,
    }

  ]
}

export default levelOne